# Generated by Django 3.1.5 on 2021-01-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210115_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('Gov', 'Government'), ('NGO', 'NGO')], max_length=16),
        ),
    ]
