# Generated by Django 3.1.5 on 2021-01-16 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stories',
            old_name='author',
            new_name='story_author',
        ),
        migrations.RenameField(
            model_name='stories',
            old_name='content',
            new_name='story_content',
        ),
        migrations.RenameField(
            model_name='stories',
            old_name='date_posted',
            new_name='story_date_posted',
        ),
        migrations.RenameField(
            model_name='stories',
            old_name='image',
            new_name='story_image',
        ),
        migrations.RenameField(
            model_name='stories',
            old_name='title',
            new_name='story_title',
        ),
    ]
