# Generated by Django 3.1.5 on 2021-01-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20210116_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='story_image',
            field=models.ImageField(default='default1.jpg', upload_to='success_stories'),
        ),
    ]
