# Generated by Django 3.1.5 on 2021-01-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngoprofile',
            old_name='ngouser',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='ngoprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='ngo_profile_pics'),
        ),
    ]
