# Generated by Django 3.1.5 on 2021-01-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_auto_20210115_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngoprofile',
            old_name='user',
            new_name='ngouser',
        ),
    ]
